services:
  notification_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aezakmi_task-notification_service"
    environment:
      AEZAKMI_TEST_CONFIG_PATH: "./configs/app.docker.toml"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  ai_analyzer_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aezakmi_task-ai_analyzer_service"
    environment:
      AEZAKMI_TEST_CONFIG_PATH: "./configs/app.docker.toml"
    command: "uv run celery -A aezakmi_task.tasks.ai_tasks worker --loglevel=info"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db_migrations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "aezakmi_task-db_migrations"
    environment:
      AEZAKMI_TEST_CONFIG_PATH: "./configs/app.docker.toml"
    command: "uv run alembic upgrade head"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.0-alpine3.18
    container_name: "aezakmi_task-db"
    env_file:
      - configs/db.env
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7.2.4-alpine
    container_name: "aezakmi_task-redis"
    ports:
      - "127.0.0.1:6379:6379"
    restart: "unless-stopped"
    volumes:
      - "./configs/:/usr/local/etc/redis"
      - "/opt/aezakmi_task/redis/data:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  prometheus_data:
  grafana_data:
  postgres_data:
